import { db, productsTable } from "@workspace/db";

const newProducts = [
  // ── VELO – Bicycles ─────────────────────────────────────────────
  {
    slug: "velo-urban-glide-pro-28",
    name: "Urban Glide Pro 28\"",
    price: 289,
    oldPrice: null,
    category: "Pilsēta",
    engine: "Mehāniskais",
    image: "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 8,
    descriptionLv: "Viegls un ērts pilsētas velosipēds, ideāls ikdienas braucieniem. 28\" riteņi nodrošina vienmērīgu braukšanu pa pilsētas ceļiem.",
    descriptionEn: "Light and comfortable city bike, ideal for daily commuting. 28\" wheels for smooth riding on city roads.",
    descriptionRu: "Лёгкий и удобный городской велосипед для ежедневных поездок. Колёса 28\" обеспечивают плавную езду по городским дорогам.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "28\"" },
      { label: { lv: "Ātrumi", en: "Speeds", ru: "Скорости" }, value: "21" },
      { label: { lv: "Rāmja materiāls", en: "Frame Material", ru: "Материал рамы" }, value: "Alumīnijs" },
      { label: { lv: "Bremzes", en: "Brakes", ru: "Тормоза" }, value: "V-Brake" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn." },
    ],
  },
  {
    slug: "velo-trail-blazer-mtb-29",
    name: "Trail Blazer MTB 29",
    price: 549,
    oldPrice: null,
    category: "Kalns",
    engine: "Mehāniskais",
    image: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 5,
    descriptionLv: "Jaudīgs kalnu velosipēds ar 29\" riteņiem. Ideāls gan meža takām, gan pilsētas ceļiem. Hydrauliskās diska bremzes.",
    descriptionEn: "Powerful mountain bike with 29\" wheels. Perfect for forest trails and city roads alike. Hydraulic disc brakes.",
    descriptionRu: "Мощный горный велосипед с колёсами 29\". Идеален как для лесных троп, так и для городских дорог. Гидравлические дисковые тормоза.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "29\"" },
      { label: { lv: "Ātrumi", en: "Speeds", ru: "Скорости" }, value: "27" },
      { label: { lv: "Amortizators", en: "Suspension", ru: "Амортизатор" }, value: "Priekšējais 120mm" },
      { label: { lv: "Bremzes", en: "Brakes", ru: "Тормоза" }, value: "Hidraulikas diska" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn." },
    ],
  },
  {
    slug: "velo-e-city-commuter-250w",
    name: "E-City Commuter 250W",
    price: 1290,
    oldPrice: null,
    category: "Elektro",
    engine: "Elektriskais",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=900&auto=format&fit=crop",
    badge: "Elektro",
    stock: 4,
    descriptionLv: "Elektriskais pilsētas velosipēds ar 250W motoru. Uzlādējams akumulators nodrošina līdz 80 km diapazonu.",
    descriptionEn: "Electric city bike with 250W motor. Rechargeable battery provides up to 80 km range.",
    descriptionRu: "Электрический городской велосипед с мотором 250 Вт. Перезаряжаемый аккумулятор обеспечивает до 80 км запаса хода.",
    specs: [
      { label: { lv: "Motors", en: "Motor", ru: "Мотор" }, value: "250W" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈80 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "25 km/h" },
      { label: { lv: "Akumulators", en: "Battery", ru: "Аккумулятор" }, value: "36V 13Ah" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn." },
    ],
  },
  {
    slug: "velo-speed-road-carbon",
    name: "Speed Road Carbon",
    price: 899,
    oldPrice: 999,
    category: "Šoseja",
    engine: "Mehāniskais",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 3,
    descriptionLv: "Viegls šosejas velosipēds ar oglekļšķiedras dakšu. Shimano Claris 16 pārnesumi, ātrs un jautrs brauciens.",
    descriptionEn: "Lightweight road bike with carbon fork. Shimano Claris 16-speed gearing, fast and fun to ride.",
    descriptionRu: "Лёгкий шоссейный велосипед с карбоновой вилкой. Shimano Claris 16 передач — быстрая и весёлая езда.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "700c" },
      { label: { lv: "Ātrumi", en: "Speeds", ru: "Скорости" }, value: "16 (Shimano Claris)" },
      { label: { lv: "Dakša", en: "Fork", ru: "Вилка" }, value: "Karbona" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "9.2 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn." },
    ],
  },
  {
    slug: "velo-kids-ranger-20",
    name: "Kids Ranger 20\"",
    price: 149,
    oldPrice: null,
    category: "Bērniem",
    engine: "Bērnu",
    image: "https://images.unsplash.com/photo-1519583272095-6433daf26b6e?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 10,
    descriptionLv: "Bērnu velosipēds no 6 gadiem ar 20\" riteņiem. Regulējams sēdeklis un stūre. Drošas V-Brake bremzes.",
    descriptionEn: "Kids' bike from age 6 with 20\" wheels. Adjustable seat and handlebar. Safe V-Brake brakes.",
    descriptionRu: "Детский велосипед с 6 лет с колёсами 20\". Регулируемое сиденье и руль. Безопасные V-Brake тормоза.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "20\"" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "6-10" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "11 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "velo-gravel-master-x1",
    name: "Gravel Master X1",
    price: 749,
    oldPrice: null,
    category: "Kalns",
    engine: "Mehāniskais",
    image: "https://images.unsplash.com/photo-1502743780242-f10d2ce370f3?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 4,
    descriptionLv: "Daudzfunkcionāls gravel velosipēds — vienādā mērā labs gan uz asfalta, gan uz grants ceļiem.",
    descriptionEn: "Versatile gravel bike — equally good on asphalt and gravel roads.",
    descriptionRu: "Многофункциональный гравийный велосипед — одинаково хорош как на асфальте, так и на грунтовых дорогах.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "700c" },
      { label: { lv: "Ātrumi", en: "Speeds", ru: "Скорости" }, value: "22 (Shimano Tiagra)" },
      { label: { lv: "Rāmja materiāls", en: "Frame Material", ru: "Материал рамы" }, value: "Chromoly tērauds" },
      { label: { lv: "Bremzes", en: "Brakes", ru: "Тормоза" }, value: "Diska" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn." },
    ],
  },
  {
    slug: "velo-retro-city-cruiser",
    name: "Retro City Cruiser",
    price: 399,
    oldPrice: null,
    category: "Pilsēta",
    engine: "Mehāniskais",
    image: "https://images.unsplash.com/photo-1511994298241-608e28f14fde?q=80&w=900&auto=format&fit=crop",
    badge: "Jauns",
    stock: 6,
    descriptionLv: "Klasiskā retro stila kruizers ar ērtu sēdekli un plašiem riteņiem. Ideāls lēnam, stilīgam braucienam pa pilsētu.",
    descriptionEn: "Classic retro-style cruiser with comfortable seat and wide tires. Ideal for a slow, stylish city ride.",
    descriptionRu: "Классический крейсер в стиле ретро с удобным седлом и широкими шинами. Идеален для неспешных стильных поездок по городу.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "26\"" },
      { label: { lv: "Ātrumi", en: "Speeds", ru: "Скорости" }, value: "7" },
      { label: { lv: "Rāmja materiāls", en: "Frame Material", ru: "Материал рамы" }, value: "Tērauds" },
      { label: { lv: "Bremzes", en: "Brakes", ru: "Тормоза" }, value: "V-Brake" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn." },
    ],
  },
  {
    slug: "velo-e-mountain-trail-500w",
    name: "E-Mountain Trail 500W",
    price: 2190,
    oldPrice: 2490,
    category: "Elektro",
    engine: "Elektriskais",
    image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?q=80&w=900&auto=format&fit=crop",
    badge: "Elektro",
    stock: 2,
    descriptionLv: "Jaudīgs elektriskais kalnu velosipēds ar 500W motoru. Bosch akumulators, hidrauliskās bremzes, pilna amortizācija.",
    descriptionEn: "Powerful electric mountain bike with 500W motor. Bosch battery, hydraulic brakes, full suspension.",
    descriptionRu: "Мощный электрический горный велосипед с мотором 500 Вт. Аккумулятор Bosch, гидравлические тормоза, полная амортизация.",
    specs: [
      { label: { lv: "Motors", en: "Motor", ru: "Мотор" }, value: "500W Bosch" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈120 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "25 km/h" },
      { label: { lv: "Akumulators", en: "Battery", ru: "Аккумулятор" }, value: "36V 14Ah" },
      { label: { lv: "Amortizators", en: "Suspension", ru: "Амортизатор" }, value: "Pilna 130mm" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn." },
    ],
  },

  // ── SKRITUĻSLIDAS – Inline Skates ────────────────────────────────
  {
    slug: "rollerblade-zetrablade-80",
    name: "Rollerblade Zetrablade 80",
    price: 119,
    oldPrice: null,
    category: "Skrituļslidas",
    engine: "Rekreācija",
    image: "https://images.unsplash.com/photo-1520045892732-304bc3ac5d8e?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 12,
    descriptionLv: "Populārākais iesācēju skrituļslidas modelis no Rollerblade. Ērti, droši un viegli apgūstami.",
    descriptionEn: "Rollerblade's most popular entry-level inline skate. Comfortable, safe, and easy to learn.",
    descriptionRu: "Самая популярная модель начального уровня от Rollerblade. Удобные, безопасные и простые в освоении.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "80mm" },
      { label: { lv: "Riteņu cietība", en: "Wheel Hardness", ru: "Жёсткость колеса" }, value: "80A" },
      { label: { lv: "Gultņi", en: "Bearings", ru: "Подшипники" }, value: "ABEC 5" },
      { label: { lv: "Pieejamie izmēri", en: "Sizes Available", ru: "Доступные размеры" }, value: "36–46" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "k2-fit-80-boa",
    name: "K2 FIT 80 Boa W",
    price: 159,
    oldPrice: null,
    category: "Skrituļslidas",
    engine: "Rekreācija",
    image: "https://images.unsplash.com/photo-1556020685-ae41abfc9365?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 8,
    descriptionLv: "Sieviešu skrituļslidas ar ērtu Boa aizdari. Lielisks komforts un kontrole pilsētas braucieniem.",
    descriptionEn: "Women's inline skates with comfortable Boa closure. Excellent comfort and control for city skating.",
    descriptionRu: "Женские роликовые коньки с удобной застёжкой Boa. Отличный комфорт и контроль для городского катания.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "80mm" },
      { label: { lv: "Aizdare", en: "Closure", ru: "Застёжка" }, value: "Boa System" },
      { label: { lv: "Gultņi", en: "Bearings", ru: "Подшипники" }, value: "ABEC 5" },
      { label: { lv: "Pieejamie izmēri", en: "Sizes Available", ru: "Доступные размеры" }, value: "36–42 (Sieviešu)" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "rollerblade-microblade-g",
    name: "Rollerblade Microblade G Kids",
    price: 79,
    oldPrice: null,
    category: "Skrituļslidas",
    engine: "Bērnu",
    image: "https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 15,
    descriptionLv: "Regulējami bērnu skrituļslidas kas aug kopā ar bērnu. Drošas un ērtas bērniem no 5 gadiem.",
    descriptionEn: "Adjustable kids' inline skates that grow with the child. Safe and comfortable for children from age 5.",
    descriptionRu: "Регулируемые детские роликовые коньки, растущие вместе с ребёнком. Безопасные и удобные для детей от 5 лет.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "72mm" },
      { label: { lv: "Regulēšana", en: "Adjustment", ru: "Регулировка" }, value: "4 izmēri (4 sizes)" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "5–12" },
      { label: { lv: "Pieejamie izmēri", en: "Sizes Available", ru: "Доступные размеры" }, value: "29–34 / 33–38" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "rollerblade-twister-edge",
    name: "Rollerblade Twister Edge",
    price: 219,
    oldPrice: 249,
    category: "Skrituļslidas",
    engine: "Fitness",
    image: "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 6,
    descriptionLv: "Fitness skrituļslidas ar 80mm riteņiem un ABEC 9 gultņiem. Augstas veiktspējas modelis pieredzējušiem braucējiem.",
    descriptionEn: "Fitness inline skates with 80mm wheels and ABEC 9 bearings. High-performance model for experienced skaters.",
    descriptionRu: "Фитнес-ролики с колёсами 80 мм и подшипниками ABEC 9. Высокопроизводительная модель для опытных роллеров.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "80mm" },
      { label: { lv: "Gultņi", en: "Bearings", ru: "Подшипники" }, value: "ABEC 9" },
      { label: { lv: "Rāmis", en: "Frame", ru: "Рама" }, value: "Alumīnijs" },
      { label: { lv: "Pieejamie izmēri", en: "Sizes Available", ru: "Доступные размеры" }, value: "36–46" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "fila-primo-2-0",
    name: "Fila Primo 2.0",
    price: 109,
    oldPrice: null,
    category: "Skrituļslidas",
    engine: "Rekreācija",
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 9,
    descriptionLv: "Ērtas rekreācijas skrituļslidas ar mīkstu oderi un stabilu brekzēšanas sistēmu. Lieliski piemērotas iesācējiem.",
    descriptionEn: "Comfortable recreational inline skates with soft liner and stable braking system. Great for beginners.",
    descriptionRu: "Удобные рекреационные ролики с мягким вкладышем и надёжной тормозной системой. Отлично подходят для начинающих.",
    specs: [
      { label: { lv: "Riteņa izmērs", en: "Wheel Size", ru: "Размер колеса" }, value: "76mm" },
      { label: { lv: "Riteņu cietība", en: "Wheel Hardness", ru: "Жёсткость колеса" }, value: "82A" },
      { label: { lv: "Gultņi", en: "Bearings", ru: "Подшипники" }, value: "ABEC 5" },
      { label: { lv: "Pieejamie izmēri", en: "Sizes Available", ru: "Доступные размеры" }, value: "35–46" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },

  // ── ZIEMAS SPORTS – Winter Sports ────────────────────────────────
  {
    slug: "atomic-cloud-q8-skis",
    name: "Atomic Cloud Q8 Skis",
    price: 449,
    oldPrice: 499,
    category: "Slēpošana",
    engine: "Slēpes",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 7,
    descriptionLv: "Vieglas un ērtākas slēpes iesācējiem un vidēja līmeņa slēpotājiem. QT-light sistēma atvieglo braukšanu.",
    descriptionEn: "Light and forgiving skis for beginner to intermediate skiers. QT-light system makes skiing easier.",
    descriptionRu: "Лёгкие и прощающие ошибки лыжи для начинающих и промежуточных горнолыжников. Система QT-light упрощает катание.",
    specs: [
      { label: { lv: "Garums", en: "Length", ru: "Длина" }, value: "140–170 cm" },
      { label: { lv: "Rādiuss", en: "Radius", ru: "Радиус" }, value: "12.4m" },
      { label: { lv: "Platums", en: "Width", ru: "Ширина" }, value: "72mm talp" },
      { label: { lv: "Saistītājs", en: "Binding", ru: "Крепление" }, value: "Atomic M10" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "fischer-aspire-slr-skis",
    name: "Fischer Aspire SLR Skis W",
    price: 379,
    oldPrice: null,
    category: "Slēpošana",
    engine: "Slēpes",
    image: "https://images.unsplash.com/photo-1605540436563-5bca919ae766?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 5,
    descriptionLv: "Sieviešu slēpes ar vieglu SLR kodolu un Twin Tip dizainu. Ērtas braukšanas sajūtas visos apstākļos.",
    descriptionEn: "Women's skis with lightweight SLR core and twin tip design. Comfortable ride feel in all conditions.",
    descriptionRu: "Женские лыжи с лёгким сердечником SLR и Twin Tip дизайном. Комфортные ощущения от катания в любых условиях.",
    specs: [
      { label: { lv: "Garums", en: "Length", ru: "Длина" }, value: "140–163 cm" },
      { label: { lv: "Rādiuss", en: "Radius", ru: "Радиус" }, value: "11.8m" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "1050g/ski" },
      { label: { lv: "Saistītājs", en: "Binding", ru: "Крепление" }, value: "Fischer Progressor" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "burton-ripcord-snowboard",
    name: "Burton Ripcord Snowboard",
    price: 349,
    oldPrice: null,
    category: "Snoubords",
    engine: "Snoubords",
    image: "https://images.unsplash.com/photo-1520208422220-d12a3c588574?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 6,
    descriptionLv: "Burton Ripcord — ideāls sākuma snoubords. Viegla kontrole un mīksts braukšanas veids iesācējiem.",
    descriptionEn: "Burton Ripcord — the ideal beginner snowboard. Easy control and forgiving ride for first-timers.",
    descriptionRu: "Burton Ripcord — идеальный сноуборд для начинающих. Лёгкое управление и прощающий стиль катания.",
    specs: [
      { label: { lv: "Garums", en: "Length", ru: "Длина" }, value: "145–162 cm" },
      { label: { lv: "Forma", en: "Shape", ru: "Форма" }, value: "Twin" },
      { label: { lv: "Profils", en: "Profile", ru: "Профиль" }, value: "Flat" },
      { label: { lv: "Cietība", en: "Flex", ru: "Жёсткость" }, value: "2/10 (Soft)" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "rossignol-experience-78ca",
    name: "Rossignol Experience 78CA",
    price: 329,
    oldPrice: null,
    category: "Slēpošana",
    engine: "Slēpes",
    image: "https://images.unsplash.com/photo-1598211686290-a8ef209d87c7?q=80&w=900&auto=format&fit=crop",
    badge: "Populārs",
    stock: 8,
    descriptionLv: "Rossignol Experience 78CA — visai ģimenei piemērotas slēpes ar labu kontroli uz apstrādātiem nogāzēm.",
    descriptionEn: "Rossignol Experience 78CA — family-friendly skis with great control on groomed slopes.",
    descriptionRu: "Rossignol Experience 78CA — лыжи для всей семьи с хорошим контролем на подготовленных склонах.",
    specs: [
      { label: { lv: "Garums", en: "Length", ru: "Длина" }, value: "150–176 cm" },
      { label: { lv: "Platums talp.", en: "Width Waist", ru: "Ширина в талии" }, value: "78mm" },
      { label: { lv: "Rādiuss", en: "Radius", ru: "Радиус" }, value: "13m" },
      { label: { lv: "Saistītājs", en: "Binding", ru: "Крепление" }, value: "Rossignol XP10" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
  {
    slug: "nitro-snowboard-boots-team",
    name: "Nitro Team Snowboard Boots",
    price: 189,
    oldPrice: null,
    category: "Snoubords",
    engine: "Snoubords",
    image: "https://images.unsplash.com/photo-1547327132-9a6f27e5a5e4?q=80&w=900&auto=format&fit=crop",
    badge: null,
    stock: 10,
    descriptionLv: "Nitro Team — vieglas un ērtus snouborda zābaki ar ACES Cuff un TLS saites sistēmu. Ātri apvilkšanai.",
    descriptionEn: "Nitro Team — lightweight and comfortable snowboard boots with ACES Cuff and TLS lacing. Quick to put on.",
    descriptionRu: "Nitro Team — лёгкие и удобные сноубордические ботинки с системой ACES Cuff и шнуровкой TLS. Быстро надеваются.",
    specs: [
      { label: { lv: "Cietība", en: "Flex", ru: "Жёсткость" }, value: "5/10 (Medium)" },
      { label: { lv: "Iekšzole", en: "Liner", ru: "Внутренний ботинок" }, value: "Level 1 Custom" },
      { label: { lv: "Pieejamie izmēri", en: "Sizes Available", ru: "Доступные размеры" }, value: "40–48" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn." },
    ],
  },
];

async function patch() {
  console.log("Adding new products...");
  let added = 0;
  for (const p of newProducts) {
    try {
      await db
        .insert(productsTable)
        .values(p as any)
        .onConflictDoNothing();
      added++;
      console.log(`+ ${p.name}`);
    } catch (err: any) {
      console.error(`Failed ${p.name}: ${err.message}`);
    }
  }
  console.log(`Done — added ${added} products.`);
  process.exit(0);
}

patch().catch((err) => {
  console.error(err);
  process.exit(1);
});
