import { db, productsTable } from "@workspace/db";

const products = [
  {
    slug: "zn50qt-34-f11-black-blue",
    name: "ZN50QT-34 (F11) BLACK/Blue",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/F11-B-black:blue.jpg",
    badge: "-3%",
    stock: 5,
    descriptionLv: "Stilīgs un ekonomisks skūteris ikdienas braucieniem pa pilsētu. Kompakts dizains ar jaudīgu 49cc dzinēju.",
    descriptionEn: "Stylish and economical scooter for everyday city rides. Compact design with a powerful 49cc engine.",
    descriptionRu: "Стильный и экономичный скутер для ежедневных поездок по городу. Компактный дизайн с мощным двигателем 49cc.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "95 kg" },
      { label: { lv: "Degvielas tvertne", en: "Fuel Tank", ru: "Бак" }, value: "5.5 L" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "zn50qt-34-f11-black-green",
    name: "ZN50QT-34 (F11) BLACK/Green",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/F11-G-black:green.jpg",
    badge: "-3%",
    stock: 3,
    descriptionLv: "Klasiskā F11 modeļa zaļā versija. Perfekts pilsētas skūteris ar izteiksmīgu krāsu kombināciju.",
    descriptionEn: "Green version of the classic F11 model. Perfect city scooter with an expressive color combination.",
    descriptionRu: "Зелёная версия классической модели F11. Идеальный городской скутер с выразительной цветовой комбинацией.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "95 kg" },
      { label: { lv: "Degvielas tvertne", en: "Fuel Tank", ru: "Бак" }, value: "5.5 L" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "znen-cruise-49cc-silver",
    name: "Znen Cruise 49cc Silver",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/Cruise-Silver.jpg",
    badge: "-3%",
    stock: 2,
    descriptionLv: "Retro stila krūzera skūteris ar mūsdienīgu tehnoloģiju. Ideāls braucieniem pa pilsētu un priekšpilsētu.",
    descriptionEn: "Retro-style cruiser scooter with modern technology. Ideal for city and suburban rides.",
    descriptionRu: "Скутер-крейсер в стиле ретро с современными технологиями. Идеален для поездок по городу и пригороду.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "98 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "znen-zn50qt-r8-49cc-white",
    name: "Znen ZN50QT-R8 49cc White",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/R8%20white.png",
    badge: "-3%",
    stock: 4,
    descriptionLv: "Elegantais R8 skūteris baltā krāsā — mūsdienīgs dizains un uzticama veiktspēja katru dienu.",
    descriptionEn: "The elegant R8 scooter in white — modern design and reliable daily performance.",
    descriptionRu: "Элегантный скутер R8 белого цвета — современный дизайн и надёжные характеристики на каждый день.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "92 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "zn50qt-34-f11-black-red",
    name: "ZN50QT-34 (F11) BLACK/Red",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/F11-R654-Black:Red.jpg",
    badge: "-3%",
    stock: 3,
    descriptionLv: "Agresīvā sarkanmelnā kombinācija padara F11 par izcilu izvēli tiem, kas vēlas izcelties.",
    descriptionEn: "The aggressive red-black combination makes the F11 an outstanding choice for those who want to stand out.",
    descriptionRu: "Агрессивная комбинация красного и чёрного делает F11 отличным выбором для тех, кто хочет выделиться.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "95 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "znen-zn50qt-r8-49cc-black",
    name: "Znen ZN50QT-R8 49cc Black",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/R8%20black.jpg",
    badge: "-3%",
    stock: 2,
    descriptionLv: "Melnā R8 — klasisks un bezlaicīgs. Ideāls pilsētas braucējs, kurš nepievilts.",
    descriptionEn: "The black R8 — classic and timeless. An ideal city rider that won't disappoint.",
    descriptionRu: "Чёрный R8 — классика вне времени. Идеальный городской скутер, который не разочарует.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "92 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "super-soco-tc-max",
    name: "Electro-scooter Super Soco TC MAx",
    price: 3990,
    oldPrice: null,
    category: "Elektro",
    engine: "Electric",
    image: "https://www.mobilus.lv/upload/large_max2_800x1200.jpg",
    badge: "Elektro",
    stock: 2,
    descriptionLv: "Super Soco TC MAx ir jaudīgs elektriskais skūteris ar lielu akumulatoru un iespaidīgu braukšanas diapazonu.",
    descriptionEn: "The Super Soco TC MAx is a powerful electric scooter with a large battery and impressive riding range.",
    descriptionRu: "Super Soco TC MAx — мощный электрический скутер с большим аккумулятором и впечатляющим запасом хода.",
    specs: [
      { label: { lv: "Motors", en: "Motor", ru: "Мотор" }, value: "3000W BOSCH" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈150 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "80 km/h" },
      { label: { lv: "Akumulators", en: "Battery", ru: "Аккумулятор" }, value: "60V 50Ah" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn. / months / мес." },
    ],
  },
  {
    slug: "super-soco-tc",
    name: "Electro-scooter Super Soco TC",
    price: 2990,
    oldPrice: null,
    category: "Elektro",
    engine: "Electric",
    image: "https://www.mobilus.lv/upload/large_tootepilt_TC.jpg",
    badge: "Elektro",
    stock: 3,
    descriptionLv: "Super Soco TC ir pilsētas elektriskais skūteris ar lielisku cenas/vērtības attiecību un zero emisijām.",
    descriptionEn: "The Super Soco TC is a city electric scooter with excellent value for money and zero emissions.",
    descriptionRu: "Super Soco TC — городской электрический скутер с отличным соотношением цены и качества и нулевыми выбросами.",
    specs: [
      { label: { lv: "Motors", en: "Motor", ru: "Мотор" }, value: "2000W" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈100 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "65 km/h" },
      { label: { lv: "Akumulators", en: "Battery", ru: "Аккумулятор" }, value: "60V 30Ah" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn. / months / мес." },
    ],
  },
  {
    slug: "jonway-xing-mai",
    name: "JonWay Xing Mai Electric Car",
    price: 8000,
    oldPrice: null,
    category: "Elektro",
    engine: "Electric",
    image: "https://www.mobilus.lv/upload/large_Xing%20Mai%2003.jpg",
    badge: "E-Car",
    stock: 1,
    descriptionLv: "JonWay Xing Mai ir kompakts elektriskais automobilis, ideāls pilsētas braucieniem ar nulles emisijām.",
    descriptionEn: "The JonWay Xing Mai is a compact electric car, ideal for zero-emission city driving.",
    descriptionRu: "JonWay Xing Mai — компактный электромобиль, идеальный для городских поездок с нулевыми выбросами.",
    specs: [
      { label: { lv: "Motors", en: "Motor", ru: "Мотор" }, value: "4000W" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈120 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "70 km/h" },
      { label: { lv: "Sēdvietas", en: "Seats", ru: "Мест" }, value: "2" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn. / months / мес." },
    ],
  },
  {
    slug: "motocikls-vz5",
    name: "Motocikls VZ-5 125cc",
    price: 2300,
    oldPrice: 2500,
    category: "Motocikli",
    engine: "125cc",
    image: "https://www.mobilus.lv/upload/large_3840x2400_1321159_www.ArtFile.ru_-scaled.jpg",
    badge: "-8%",
    stock: 4,
    descriptionLv: "VZ-5 ir sportisks 125cc motocikls, ideāls jaunajiem braucējiem, kuri vēlas kaut ko vairāk par skūteri.",
    descriptionEn: "The VZ-5 is a sporty 125cc motorcycle, ideal for new riders who want something more than a scooter.",
    descriptionRu: "VZ-5 — спортивный мотоцикл 125cc, идеальный для новых гонщиков, которые хотят большего, чем скутер.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "125cc" },
      { label: { lv: "Jauda", en: "Power", ru: "Мощность" }, value: "11 kW" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "110 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "148 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "cfmoto-cforce-625l",
    name: "CFMoto Cforce 625L (L7E)",
    price: 8590,
    oldPrice: null,
    category: "ATV",
    engine: "600cc",
    image: "https://www.mobilus.lv/upload/large_MY2023_CFORCE%20625_TOURING_Force%20Red_Left%2045_167.jpg",
    badge: "ATV",
    stock: 2,
    descriptionLv: "CFMoto Cforce 625L ir jaudīgs kvadracikls ar 600cc dzinēju, piemērots gan sporta, gan lauksaimniecības vajadzībām.",
    descriptionEn: "The CFMoto Cforce 625L is a powerful quad bike with a 600cc engine, suitable for both sports and agricultural use.",
    descriptionRu: "CFMoto Cforce 625L — мощный квадроцикл с двигателем 600cc, подходящий как для спорта, так и для сельского хозяйства.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "600cc EFI" },
      { label: { lv: "Jauda", en: "Power", ru: "Мощность" }, value: "41 kW" },
      { label: { lv: "Piedziņa", en: "Drive", ru: "Привод" }, value: "4WD/2WD" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "380 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "cfmoto-cforce-450l",
    name: "CFMoto CFORCE 450L",
    price: 5890,
    oldPrice: null,
    category: "ATV",
    engine: "400cc",
    image: "https://www.mobilus.lv/upload/large_MY2023_CFORCE%20450%20L_Jet%20Black_Left%2045_167.jpg",
    badge: "ATV",
    stock: 3,
    descriptionLv: "CFORCE 450L apvieno spēku un manevrētspēju. Ideāls kvadracikls gan pieredzējušiem, gan jauniem braucējiem.",
    descriptionEn: "The CFORCE 450L combines power and maneuverability. An ideal quad for both experienced and new riders.",
    descriptionRu: "CFORCE 450L сочетает мощность и маневренность. Идеальный квадроцикл для опытных и начинающих гонщиков.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "400cc EFI" },
      { label: { lv: "Jauda", en: "Power", ru: "Мощность" }, value: "28 kW" },
      { label: { lv: "Piedziņa", en: "Drive", ru: "Привод" }, value: "4WD/2WD" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "310 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "cfmoto-110-youth",
    name: "CFMoto 110 Youth ATV",
    price: 2290,
    oldPrice: null,
    category: "ATV",
    engine: "110cc",
    image: "https://www.mobilus.lv/upload/large_MY2023_CFORCE%20110_Rocket%20Red_Left%2045_CE.jpg",
    badge: "Youth",
    stock: 5,
    descriptionLv: "CFMoto 110 Youth ir drošs un jautrs kvadracikls bērniem un pusaudžiem, lai iepazītos ar ATV braukšanu.",
    descriptionEn: "The CFMoto 110 Youth is a safe and fun quad bike for children and teenagers to start their ATV journey.",
    descriptionRu: "CFMoto 110 Youth — безопасный и весёлый квадроцикл для детей и подростков, чтобы начать путь в мире ATV.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "110cc" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "40 km/h" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "10+" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "atv-pentora-110-cvt",
    name: "ATV Pentora 110 CVT KID",
    price: 1590,
    oldPrice: null,
    category: "ATV",
    engine: "110cc",
    image: "https://www.mobilus.lv/upload/large_110%20cvt%2001%20.png",
    badge: "Kids",
    stock: 4,
    descriptionLv: "Pentora 110 CVT — bērnu ATV ar automātisko pārnesumkārbu (CVT), ērti vadāms un drošs.",
    descriptionEn: "The Pentora 110 CVT is a kids' ATV with automatic transmission (CVT), easy to handle and safe.",
    descriptionRu: "Pentora 110 CVT — детский квадроцикл с автоматической коробкой передач (CVT), простой в управлении и безопасный.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "110cc CVT" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "35 km/h" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "6-12" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    slug: "atv-kayo-110-kid",
    name: "ATV Kayo 110 Kid",
    price: 1390,
    oldPrice: null,
    category: "ATV",
    engine: "110cc",
    image: "https://www.mobilus.lv/upload/large_KAYO_Warrior_110_II_ATV_Orange4.jpeg",
    badge: "Kids",
    stock: 6,
    descriptionLv: "Kayo 110 Kid ir izcils sākumpunkts jaunajiem ATV entuziastiem. Uzticams, drošs un viegli vadāms.",
    descriptionEn: "The Kayo 110 Kid is an excellent starting point for young ATV enthusiasts. Reliable, safe, and easy to ride.",
    descriptionRu: "Kayo 110 Kid — отличная отправная точка для юных любителей ATV. Надёжный, безопасный и простой в управлении.",
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "110cc" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "35 km/h" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "6-12" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
];

async function seed() {
  console.log("Seeding products...");
  for (const p of products) {
    await db
      .insert(productsTable)
      .values(p)
      .onConflictDoNothing();
  }
  console.log(`Seeded ${products.length} products.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
