export interface Product {
  id: number;
  slug: string;
  name: string;
  price: number;
  oldPrice: number | null;
  category: string;
  engine: string;
  image: string;
  badge: string | null;
  description: { lv: string; en: string; ru: string };
  specs: { label: { lv: string; en: string; ru: string }; value: string }[];
}

export const products: Product[] = [
  {
    id: 1,
    slug: "zn50qt-34-f11-black-blue",
    name: "ZN50QT-34 (F11) BLACK/Blue",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/sm_F11-B-scaled%20black:blue.jpg",
    badge: "-3%",
    description: {
      lv: "Stilīgs un ekonomisks skūteris ikdienas braucieniem pa pilsētu. Kompakts dizains ar jaudīgu 49cc dzinēju.",
      en: "Stylish and economical scooter for everyday city rides. Compact design with a powerful 49cc engine.",
      ru: "Стильный и экономичный скутер для ежедневных поездок по городу. Компактный дизайн с мощным двигателем 49cc.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "95 kg" },
      { label: { lv: "Degvielas tvertne", en: "Fuel Tank", ru: "Бак" }, value: "5.5 L" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 2,
    slug: "zn50qt-34-f11-black-green",
    name: "ZN50QT-34 (F11) BLACK/Green",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/sm_F11-G-%20black:green.jpg",
    badge: "-3%",
    description: {
      lv: "Klasiskā F11 modeļa zaļā versija. Perfekts pilsētas skūteris ar izteiksmīgu krāsu kombināciju.",
      en: "Green version of the classic F11 model. Perfect city scooter with an expressive color combination.",
      ru: "Зелёная версия классической модели F11. Идеальный городской скутер с выразительной цветовой комбинацией.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "95 kg" },
      { label: { lv: "Degvielas tvertne", en: "Fuel Tank", ru: "Бак" }, value: "5.5 L" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 3,
    slug: "znen-cruise-49cc-silver",
    name: "Znen Cruise 49CC Silver",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/sm_Group-3-1.jpeg",
    badge: "-3%",
    description: {
      lv: "Retro stila krūzera skūteris ar mūsdienīgu tehnoloģiju. Ideāls braucieniem pa pilsētu un priekšpilsētu.",
      en: "Retro-style cruiser scooter with modern technology. Ideal for city and suburban rides.",
      ru: "Скутер-крейсер в ретро-стиле с современными технологиями. Идеален для городских и пригородных поездок.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Stils", en: "Style", ru: "Стиль" }, value: "Retro Cruiser" },
      { label: { lv: "Krāsa", en: "Color", ru: "Цвет" }, value: "Silver" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 4,
    slug: "znen-zn50qt-r8-49cc-white",
    name: "ZNEN ZN50QT-R8 49cc White",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/sm_Screen%20Shot%202019-02-05%20at%2013.46.33.png",
    badge: "-3%",
    description: {
      lv: "Elegantais R8 skūteris baltā krāsā — mūsdienīgs dizains un uzticama veiktspēja katru dienu.",
      en: "The elegant R8 scooter in white — modern design and reliable daily performance.",
      ru: "Элегантный скутер R8 белого цвета — современный дизайн и надёжные характеристики на каждый день.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "92 kg" },
      { label: { lv: "Riepu izmērs", en: "Tyre Size", ru: "Размер шин" }, value: "120/70-12" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 5,
    slug: "zn50qt-34-f11-black-red",
    name: "ZN50QT-34 (F11) BLACK/Red",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/sm_F11-R654-%20Black:Red.jpg",
    badge: "-3%",
    description: {
      lv: "Agresīvā sarkanmelnā kombinācija padara F11 par izcilu izvēli tiem, kas vēlas izcelties.",
      en: "The aggressive red-black combination makes the F11 an outstanding choice for those who want to stand out.",
      ru: "Агрессивная красно-чёрная комбинация делает F11 отличным выбором для тех, кто хочет выделиться.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "95 kg" },
      { label: { lv: "Degvielas tvertne", en: "Fuel Tank", ru: "Бак" }, value: "5.5 L" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 6,
    slug: "znen-zn50qt-r8-49cc-black",
    name: "ZNEN ZN50QT-R8 49cc Black",
    price: 1950,
    oldPrice: 2000,
    category: "Skūteri",
    engine: "49cc",
    image: "https://www.mobilus.lv/upload/sm_R8%20black%5B14642%5D.jpg",
    badge: "-3%",
    description: {
      lv: "Melnā R8 — klasisks un bezlaicīgs. Ideāls pilsētas braucējs, kurš nepievilts.",
      en: "The black R8 — classic and timeless. An ideal city rider that won't disappoint.",
      ru: "Чёрный R8 — классический и вневременной. Идеальный городской скутер, который не подведёт.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "49cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "92 kg" },
      { label: { lv: "Krāsa", en: "Color", ru: "Цвет" }, value: "Matte Black" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 7,
    slug: "super-soco-tc-max",
    name: "Electro-scooter Super Soco TC MAx",
    price: 3990,
    oldPrice: null,
    category: "Elektro",
    engine: "Electric",
    image: "https://www.mobilus.lv/upload/sm_max2_800x1200.jpg",
    badge: "Elektro",
    description: {
      lv: "Super Soco TC MAx ir jaudīgs elektriskais skūteris ar lielu akumulatoru un iespaidīgu braukšanas diapazonu.",
      en: "The Super Soco TC MAx is a powerful electric scooter with a large battery and impressive riding range.",
      ru: "Super Soco TC MAx — мощный электрический скутер с большой батареей и впечатляющим запасом хода.",
    },
    specs: [
      { label: { lv: "Motors", en: "Motor", ru: "Мотор" }, value: "3000W BOSCH" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈150 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "100 km/h" },
      { label: { lv: "Uzlāde", en: "Charge Time", ru: "Зарядка" }, value: "6-8 h" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn. / months / мес." },
    ],
  },
  {
    id: 8,
    slug: "super-soco-tc",
    name: "Elektro-scooter SUPER SOCO TC",
    price: 2990,
    oldPrice: null,
    category: "Elektro",
    engine: "Electric",
    image: "https://www.mobilus.lv/upload/sm_tootepilt_TC.jpg",
    badge: "Elektro",
    description: {
      lv: "Super Soco TC ir pilsētas elektriskais skūteris ar lielisku cenas/vērtības attiecību un zero emisijām.",
      en: "The Super Soco TC is a city electric scooter with excellent value for money and zero emissions.",
      ru: "Super Soco TC — городской электроскутер с отличным соотношением цены и качества и нулевыми выбросами.",
    },
    specs: [
      { label: { lv: "Motors", en: "Motor", ru: "Мотор" }, value: "1500W" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈65 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "45 km/h" },
      { label: { lv: "Uzlāde", en: "Charge Time", ru: "Зарядка" }, value: "4-6 h" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn. / months / мес." },
    ],
  },
  {
    id: 9,
    slug: "jonway-xing-mai",
    name: "E-Car JonWay Xing Mai",
    price: 8000,
    oldPrice: null,
    category: "Elektro",
    engine: "Electric",
    image: "https://www.mobilus.lv/upload/sm_Xing%20Mai%2001.jpg",
    badge: "E-Car",
    description: {
      lv: "JonWay Xing Mai ir kompakts elektriskais automobilis, ideāls pilsētas braucieniem ar nulles emisijām.",
      en: "The JonWay Xing Mai is a compact electric car, ideal for zero-emission city driving.",
      ru: "JonWay Xing Mai — компактный электромобиль, идеальный для городских поездок с нулевыми выбросами.",
    },
    specs: [
      { label: { lv: "Tips", en: "Type", ru: "Тип" }, value: "Electric Car (L7E)" },
      { label: { lv: "Diapazons", en: "Range", ru: "Запас хода" }, value: "≈150 km" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "100 km/h" },
      { label: { lv: "Sēdvietas", en: "Seats", ru: "Кол-во мест" }, value: "2" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "24 mēn. / months / мес." },
    ],
  },
  {
    id: 10,
    slug: "motocikls-vz5",
    name: "Motocikls VZ-5 (ZY125-15A)",
    price: 2300,
    oldPrice: 2500,
    category: "Motocikli",
    engine: "125cc",
    image: "https://www.mobilus.lv/upload/sm_3840x2400_1321159_www.ArtFile.ru_-scaled.jpg",
    badge: "-8%",
    description: {
      lv: "VZ-5 ir sportisks 125cc motocikls, ideāls jaunajiem braucējiem, kuri vēlas kaut ko vairāk par skūteri.",
      en: "The VZ-5 is a sporty 125cc motorcycle, ideal for new riders who want something more than a scooter.",
      ru: "VZ-5 — спортивный мотоцикл 125cc, идеальный для начинающих гонщиков, которые хотят большего, чем скутер.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "125cc 4-stroke" },
      { label: { lv: "Jauda", en: "Power", ru: "Мощность" }, value: "8.5 kW" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "95 km/h" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "118 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 11,
    slug: "cfmoto-cforce-625l",
    name: "CFMoto Cforce 625L (l7E)",
    price: 8590,
    oldPrice: null,
    category: "ATV",
    engine: "600cc",
    image: "https://www.mobilus.lv/upload/sm_MY2023_CFORCE%20625_TOURING_Force%20Red_Left%2045_167.jpg",
    badge: "ATV",
    description: {
      lv: "CFMoto Cforce 625L ir jaudīgs kvadracikls ar 600cc dzinēju, piemērots gan sporta, gan lauksaimniecības vajadzībām.",
      en: "The CFMoto Cforce 625L is a powerful quad bike with a 600cc engine, suitable for both sports and agricultural use.",
      ru: "CFMoto Cforce 625L — мощный квадроцикл с двигателем 600cc, подходящий как для спорта, так и для сельского хозяйства.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "600cc EFI" },
      { label: { lv: "Jauda", en: "Power", ru: "Мощность" }, value: "41 kW" },
      { label: { lv: "Piedziņa", en: "Drive", ru: "Привод" }, value: "4WD/2WD" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "389 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 12,
    slug: "cfmoto-cforce-450l",
    name: "CFMoto CFORCE 450L",
    price: 5890,
    oldPrice: null,
    category: "ATV",
    engine: "400cc",
    image: "https://www.mobilus.lv/upload/sm_CF400AU-3L-S-GREEN-1.jpeg",
    badge: "ATV",
    description: {
      lv: "CFORCE 450L apvieno spēku un manevrētspēju. Ideāls kvadracikls gan pieredzējušiem, gan jauniem braucējiem.",
      en: "The CFORCE 450L combines power and maneuverability. An ideal quad for both experienced and new riders.",
      ru: "CFORCE 450L сочетает мощь и манёвренность. Идеальный квадроцикл как для опытных, так и для начинающих.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "400cc EFI" },
      { label: { lv: "Jauda", en: "Power", ru: "Мощность" }, value: "25 kW" },
      { label: { lv: "Piedziņa", en: "Drive", ru: "Привод" }, value: "4WD/2WD" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "316 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 13,
    slug: "cfmoto-110-youth",
    name: "CFMoto 110 Youth",
    price: 2290,
    oldPrice: null,
    category: "ATV",
    engine: "110cc",
    image: "https://www.mobilus.lv/upload/sm_MY2023_CFORCE%20110_Rocket%20Red_Left%2045_CE.jpg",
    badge: "Youth",
    description: {
      lv: "CFMoto 110 Youth ir drošs un jautrs kvadracikls bērniem un pusaudžiem, lai iepazītos ar ATV braukšanu.",
      en: "The CFMoto 110 Youth is a safe and fun quad bike for children and teenagers to start their ATV journey.",
      ru: "CFMoto 110 Youth — безопасный и весёлый квадроцикл для детей и подростков, чтобы познакомиться с ATV.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "110cc 4-stroke" },
      { label: { lv: "Ātrums maks.", en: "Max Speed", ru: "Макс. скорость" }, value: "55 km/h" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "10+" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "165 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 14,
    slug: "atv-pentora-110-cvt",
    name: "ATV Pentora 110 CVT KID",
    price: 1590,
    oldPrice: null,
    category: "ATV",
    engine: "110cc",
    image: "https://www.mobilus.lv/upload/sm_110%20cvt%2001%20.png",
    badge: "Kids",
    description: {
      lv: "Pentora 110 CVT — bērnu ATV ar automātisko pārnesumkārbu (CVT), ērti vadāms un drošs.",
      en: "The Pentora 110 CVT is a kids' ATV with automatic transmission (CVT), easy to handle and safe.",
      ru: "Pentora 110 CVT — детский квадроцикл с автоматической трансмиссией (CVT), удобный в управлении и безопасный.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "110cc CVT" },
      { label: { lv: "Pārnesumkārba", en: "Transmission", ru: "Трансмиссия" }, value: "Automatic CVT" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "6-12" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "140 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
  {
    id: 15,
    slug: "atv-kayo-110-kid",
    name: "ATV Kayo 110 Kid",
    price: 1390,
    oldPrice: null,
    category: "ATV",
    engine: "110cc",
    image: "https://www.mobilus.lv/upload/sm_KAYO%20AT110%201.jpeg",
    badge: "Kids",
    description: {
      lv: "Kayo 110 Kid ir izcils sākumpunkts jaunajiem ATV entuziastiem. Uzticams, drošs un viegli vadāms.",
      en: "The Kayo 110 Kid is an excellent starting point for young ATV enthusiasts. Reliable, safe, and easy to ride.",
      ru: "Kayo 110 Kid — отличная отправная точка для юных любителей квадроциклов. Надёжный, безопасный и простой в управлении.",
    },
    specs: [
      { label: { lv: "Dzinējs", en: "Engine", ru: "Двигатель" }, value: "110cc 4-stroke" },
      { label: { lv: "Pārnesumkārba", en: "Transmission", ru: "Трансмиссия" }, value: "Auto + Reverse" },
      { label: { lv: "Vecums", en: "Age", ru: "Возраст" }, value: "6-12" },
      { label: { lv: "Svars", en: "Weight", ru: "Вес" }, value: "135 kg" },
      { label: { lv: "Garantija", en: "Warranty", ru: "Гарантия" }, value: "12 mēn. / months / мес." },
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
